# Generated by Django 3.2.3 on 2021-05-26 11:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='제목', max_length=40)),
                ('body', models.TextField(help_text='포스트 본문 내용')),
                ('show', models.CharField(choices=[('public', 'PUBLIC'), ('private', 'PRIVATE'), ('my', 'MY')], default='public', help_text='비공개 여부', max_length=10)),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
